version: "3.8"

services:
  nodejs:
    container_name: nodejs
    build: .  
    ports:
      - "5000:5000"
    restart: "on-failure"
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  
    restart: "on-failure"  